#!/usr/bin/sh
clear

fn=`ls -t | head -1`
REPOSITORY=repo2

GIT_ADD() {
clear
		echo -e "\tPerforming a 'GIT ADD' on repository $respository\nHIT ENTER TO CONTINUE"
		read
		git add $fn

# fns=$(ls -lt | awk '{print $NF}' | tr -d '[0-9]')
}

GIT_ADD_ALL() {
clear
		echo -e "\tPerforming a 'GIT ADD' on repository $respository\nHIT ENTER TO CONTINUE"
		read
		git add .

# fns=$(ls -lt | awk '{print $NF}' | tr -d '[0-9]')
}

GIT_PULL() {
clear 
		git pull 
}

GIT_STATUS() {
clear
		# echo -e "\tPerforming a 'GIT STATUS' on repository $respository\nHIT ENTER TO CONTINUE"
		# read
		git status 
}

GIT_PUSH() {
clear 
		git push 
}

GIT_COMMIT() {
clear
		git commit -m "Updated file $fn"
}

GIT_CLONE() {
clear
		echo -e "\tPerforming a 'GIT CLONE' on repository $respository\nHIT ENTER TO CONTINUE"
		read

		echo "cd $HOME; mv $HOME/$REPOSITORY $HOME/$REPOSITORY.`date +%Y%m%d`.bk"
		echo "git clone git@github.com marlonthomas53/$REPOSITORY"
		echo "cd $HOME/$REPOSITORY"
		pwd
}

GIT_DIFF() {
clear
		git diff 
}

###### MAIN 

PS3="INPUT: HIT ENTER -> "
select choice in \
"GIT_STATUS" \
"GIT_PULL" \
"GIT_ADD" \
"GIT_ADD_ALL" \
"GIT_COMMIT" \
"GIT_PUSH" \
"GIT_DIFF" \
"GIT_CLONE" \
"EXIT_GIT_MENU" 

do
for options in $(echo $choice)
do
case $options in
    "GIT_STATUS")
        GIT_STATUS
;;
    "GIT_PULL")
        GIT_PULL
;;
    "GIT_ADD")
        GIT_ADD
;;
    "GIT_ADD_ALL")
        GIT_ADD_ALL
;;
    "GIT_COMMIT")
        GIT_COMMIT
;;
    "GIT_PUSH")
        GIT_PUSH
;;
    "GIT_DIFF")
        GIT_DIFF
;;
    "GIT_CLONE")
        GIT_CLONE
;;
    "EXIT_GIT_MENU")
        clear
        echo -e "\n\t\tEXITING_GIT_MENU"
				sleep 1
        exit 0
;;
esac
done
        done
